version: '3.9'

services:
  app:
    build: .
    container_name: 'auth-express-example'
    env_file:
      - '.env'
    ports:
      - 3000:${PORT}
    volumes:
      - ./:/app
    links:
      - db
    command: pnpm dev

  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    expose:
      - 27017
    deploy:
      restart_policy:
        condition: on-failure
